// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function EncryptPDF(arg1:gui.EncryptPayload):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RandomPassword():Promise<string>;

export function SaveFileDialog():Promise<string>;

export function UI_EncryptionFinished(arg1:boolean,arg2:Error):Promise<void>;

export function UI_UpdateOutputPath():Promise<void>;
