// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptPDF(arg1) {
  return window['go']['gui']['App']['EncryptPDF'](arg1);
}

export function Greet(arg1) {
  return window['go']['gui']['App']['Greet'](arg1);
}

export function IsReady() {
  return window['go']['gui']['App']['IsReady']();
}

export function OpenFileDialog() {
  return window['go']['gui']['App']['OpenFileDialog']();
}

export function RandomPassword() {
  return window['go']['gui']['App']['RandomPassword']();
}

export function SaveFileDialog() {
  return window['go']['gui']['App']['SaveFileDialog']();
}

export function UI_EncryptionFinished(arg1, arg2) {
  return window['go']['gui']['App']['UI_EncryptionFinished'](arg1, arg2);
}

export function UI_UpdateOutputPath() {
  return window['go']['gui']['App']['UI_UpdateOutputPath']();
}
